### ISSUE TITLE
err msg

### ISSUE THREAD

**Issue by wangbokun** [samuelebistoletti/docker-statsd-influxdb-grafana#4]
hi,

$ docker logs 5e46df5cb8779146d71f2571f5ef13684967a2c033b75b62b53fa68714f9fe24
**\* Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
**\* Running /etc/my_init.d/01_run_mysql.sh...
=> Starting MySQL ...
- Starting MySQL database server mysqld
  ...done.
- Checking for tables which need an upgrade, are corrupt or were 
  not closed cleanly.
  **\* Running /etc/my_init.d/02_run_influxdb.sh...
  => Starting InfluxDB ...
  /etc/init.d/influxdb: line 157: ulimit: open files: cannot modify limit: Operation not permitted
  set open file limit to 65536 [ FAILED ]
  **\* /etc/my_init.d/02_run_influxdb.sh failed with status 1

**\* Killing all processes...

**Comment by samuelebistoletti** [comment]
Hi,
it is not an issue related to the Docker container itself, quite the opposite, the problem is your host configuration where you installed Docker. The solution is to raise open file limit on your host OS, after stopping Docker, reboot host and relaunch the container. For security reason Docker doesn't allow containers to change open file limit on the host.

See this: http://stackoverflow.com/questions/24318543/how-to-set-ulimit-file-descriptor-on-docker-container-the-image-tag-is-phusion
